//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("Gumba")]
[assembly: AssemblyCompany("InfoTeCS")]
[assembly: AssemblyCopyright("Copyright 2013 InfoTeCS")]
[assembly: AssemblyTrademark("Gumba")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]



